# Generated by Django 5.1.5 on 2025-01-23 22:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=30)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_trx',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipotrx', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.IntegerField(blank=True, default=100, max_length=15, null=True)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(max_length=100)),
                ('fecha_transaccion', models.DateTimeField(default=datetime.date.today)),
                ('accion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolsa.accion')),
                ('tipotrx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolsa.tipo_trx')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
