# Generated by Django 5.1.5 on 2025-01-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='saldo',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
