# Generated by Django 5.1.5 on 2025-01-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_alter_perfilusuario_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='cambio_porcentual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accion',
            name='precio_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='Precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
